name: 'Terraform Plan'
on:
  # TODO: using this to test my branch. remove before pull request
  push:
    branches:
      - feature/issue-22_fix-ci
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: Lint Terraform
        uses: actionshub/terraform-lint@master
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'src/root'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.12.13
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: 'src/root'
        env:
          TF_VAR_NAME: 'cipool'
          TF_VAR_LOCATION: 'centraulus'
          TF_VAR_COSMOS_RU: 1000
          TF_VAR_CONTAINER_FILE_NAME: 'benchmark.json'
          TF_VAR_SLEEP_TIME: 125
          TF_VAR_INSTANCES: '{"sherberttst" = "typescript"}'
          #Must create SP with Subscription Contributor Rights to run TF with
          TF_VAR_TF_CLIENT_ID: 'f7385c02-d00f-4466-8d51-27838063d906'
          TF_VAR_TF_CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
          TF_VAR_TF_TENANT_ID: '72f988bf-86f1-41af-91ab-2d7cd011db47'
          TF_VAR_TF_SUB_ID: '648dcb5a-de1e-48b2-af6b-fe6ef28d355c'
          TF_VAR_ACTION_GROUP_NAME: 'alert_list'
          TF_VAR_EMAIL_FOR_ALERTS: 'test@test.com'
          TF_VAR_RT_THRESHOLD: '50'
          TF_VAR_RT_OPERATOR: 'GreaterThan'
          TF_VAR_RT_SEVERITY: '3'
          TF_VAR_RT_FREQUENCY: 'PT5M'
          TF_VAR_RT_WINDOW_SIZE: 'PT15M'
          TF_VAR_MR_THRESHOLD: '50'
          TF_VAR_MR_OPERATOR: 'GreaterThan'
          TF_VAR_MR_SEVERITY: '3'
          TF_VAR_MR_FREQUENCY: 'PT5M'
          TF_VAR_MR_WINDOW_SIZE: 'PT15M'
          TF_VAR_WT_THRESHOLD: '1'
          TF_VAR_WT_OPERATOR: 'LessThan'
          TF_VAR_WT_SEVERITY: '2'
          TF_VAR_WT_FREQUENCY: 'PT5M'
          TF_VAR_WT_WINDOW_SIZE: 'PT15M'
          TF_VAR_WV_THRESHOLD: '1'
          TF_VAR_WV_OPERATOR: 'LessThan'
          TF_VAR_WV_SEVERITY: '2'
          TF_VAR_WV_FREQUENCY: 'PT5M'
          TF_VAR_WV_WINDOW_SIZE: 'PT15M'
          #Must Create Log Anayltics workspace prior to deployment
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
