name: 'Terraform Plan'
on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: Lint Terraform
        uses: actionshub/terraform-lint@master
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.13.0
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: 'src/root'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 0.13.0
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: 'src/root'
        env:
          TF_VAR_NAME: 'cipool'
          TF_VAR_LOCATION: 'centralus'
          TF_VAR_COSMOS_RU: 1000
          TF_VAR_CONTAINER_FILE_NAME: 'benchmark.json'
          TF_VAR_SLEEP_TIME: 125
          TF_VAR_INSTANCES: '{"sherberttst" = "typescript"}'
          #Must create SP with Subscription Contributor Rights to run TF with
          TF_VAR_TF_CLIENT_ID: 'f7385c02-d00f-4466-8d51-27838063d906'
          TF_VAR_TF_CLIENT_SECRET: ${{ secrets.SP_CLIENT_SECRET }}
          TF_VAR_TF_TENANT_ID: '72f988bf-86f1-41af-91ab-2d7cd011db47'
          TF_VAR_TF_SUB_ID: '648dcb5a-de1e-48b2-af6b-fe6ef28d355c'
          TF_VAR_ACTION_GROUP_NAME: 'alert_list'
          TF_VAR_EMAIL_FOR_ALERTS: 'test@test.com'
          TF_VAR_ACR_SP_ID: '00000000-0000-0000-0000-000000000000'
          TF_VAR_ACR_SP_SECRET: 'testvalue'
          TF_VAR_WEBV_INSTANCES: '{"centralus" = "1000"}'
          TF_VAR_ALERT_RULES: |-
            {
              rt_alerts = {
                name        = "response-time-alert"
                frequency   = "PT5M"
                window_size = "PT15M"
                description = "Server Response Time Too High"
                severity    = 3
                enabled     = false
                operator    = "GreaterThan"
                threshold   = "50"
                aggregation = "Average"
                metric_name = "requests/duration"
              }
            }
          TF_VAR_WEBTEST_ALERT_RULES: |-
            {
              wt_rules = {
                name        = "web-test-alert"
                frequency   = "PT5M"
                window_size = "PT15M"
                description = "Web Test Alert"
                severity    = 2
                enabled     = false
                operator    = "LessThan"
                threshold   = "1"
                aggregation = "Average"
                metric_name = "availabilityResults/availabilityPercentage"
              }
            }
          #Must Create Log Anayltics workspace prior to deployment
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
